### ISSUE TITLE
Email validation rejects valid emails

### ISSUE THREAD

**Issue by benhsm** [opportunity-hack/evs#1]
The site's email validation is currently rejecting many common types of valid emails, e.g. those with subdomains or hyphens in them. This is because of the way that zod's `z.string().email()` currently works. This has been fixed in the latest versions of zod, but the latest release hasn't caught up yet.

**Comment by gregv** [comment]
![image](https://github.com/opportunity-hack/evs/assets/6913307/dfe5ad11-1497-4db6-ac90-800c2b129b31)

Likely resolved in this update - closing
