### ISSUE TITLE
No links for Terms of Service and Privacy Policy

### ISSUE THREAD

**Issue by parkerdavis1** [opportunity-hack/evs#10]
Once the TOS and PP are finalized make sure to link them during onboarding.

**Comment by parkerdavis1** [comment]
The links have been added with PR https://github.com/opportunity-hack/evs/pull/17. The TOS and PP still need to be written.

**Comment by gregv** [comment]
Ty @parkerdavis1 
![image](https://github.com/opportunity-hack/evs/assets/6913307/f34efcdc-9b19-4fa5-8a43-d51a260acb4d)
