### ISSUE TITLE
Refactor: make 'instructor' into a distinct role with its own permissions

### ISSUE THREAD

**Issue by benhsm** [opportunity-hack/evs#11]
Right now, whether user is an instructor or not is being tracked with a boolean value on the User DB model when it really ought to be tracked as a role in the same way that the admin role is implemented. This needs to be changed in all the routes that refer to instructors without breaking existing functionality.

**Comment by AceGabrielFigueroa** [comment]
was this fixed on this 4e722ff commit?

**Comment by benhsm** [comment]
Yes, thanks for pointing this out
