### ISSUE TITLE
Show spots open on calendar event

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/evs#14]
1. I love the calendar view! It would be great (I think this was mentioned by Greg earlier) if before anyone clicks on a spot to be able to see how many spots are open.

See @benhsm's response on [Slack here](https://opportunity-hack.slack.com/archives/C01CMCF4BUN/p1688697090652109?thread_ts=1688675690.117329&cid=C01CMCF4BUN)
- With the current setup, it is unfortunately difficult to make this information available at a glance, before clicking on an event. The calendar is arguably the most complex component of the program and truthfully, I don't see a good way of doing this that wouldn't resemble rebuilding it ourselves from scratch. I'd expect this might take a lot of time.
- However, it would be quite feasible to add a button that changes the calendar to show only events that have vacancies.
- Another feasible option would be to add an alternative view of events that might look more like a list or gallery of cards rather than a graphical calendar.

(Terrible/Rough) Example of what we're going for
<img width="1154" alt="The_Barn_-_Volunteer_Portal" src="https://github.com/opportunity-hack/evs/assets/6913307/5eb9e849-0e49-43e8-8794-32ee2e7e8fe8">

**Comment by benhsm** [comment]
In the meanwhile, I've gone ahead and implemented the alternative mentioned in the second bullet point (61516902d775cffcce8560e292a03dd09a0eb56b):

![image](https://github.com/opportunity-hack/evs/assets/93843523/1a52801a-dcf0-4de6-a4af-3d643b218372)

**Comment by parkerdavis1** [comment]
I have added this functionality to the Agenda view. The open slots only display on events that are still upcoming. 
9f762fdc63b93842f2ceb7f6f472386ee86f526f
17eb256e687989b7ddc02373c3e257d7e52dc066
0aab36eeb574fa069ff9d217cb4c41ba417b0ab7
0d56cdf5f43dcb555c788751232dbf528db9cbd9

![Screen Shot 2023-12-28 at 13 28 45](https://github.com/opportunity-hack/evs/assets/92223355/061936ee-c8ae-41c0-bb07-365a6da66867)

**Comment by gregv** [comment]
@parkerdavis1 swooshed this one - closing
