### ISSUE TITLE
Admin Visibility of Certain Events

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/evs#15]
As an admin, I'd like to use the same calendar for all of my events.  Sometimes we schedule birthdays which should not be visible to others, but only admins.

See this post in [Slack here](https://opportunity-hack.slack.com/archives/C01CMCF4BUN/p1688697090652109?thread_ts=1688675690.117329&cid=C01CMCF4BUN)
5. Is there a way to have an admin calendar separate from the volunteer calendar? Birthday party helpers are usually scheduled by the director but I think it would be amazing to have the ability on the calendar just not necessarily seen by volunteers.
- This is possible, but I can also display different sets of events on the existing calendar depending on whether the viewer is an admin or a volunteer, if that would work as well. This would mean adding a checkbox to the form for creating an event that you would check to mark it as visible or invisible to volunteers.

Example:
If an admin labels this event to be visible only to admins, this would not be displayed in the calendar

<img width="191" alt="image" src="https://github.com/opportunity-hack/evs/assets/6913307/0a5f6568-8bcb-421b-8475-832e9c9d01ff">

<img width="722" alt="image" src="https://github.com/opportunity-hack/evs/assets/6913307/5c94e9df-ba7c-49f3-b970-8c53909c0324">

**Comment by benhsm** [comment]
I think this is addressed by a feature introduced in 424f0d1bf6dd73c61898d9fbb2ce533899d5fc94 that adds a toggle in event creation or updating that makes an event visible only to admin users (the checkbox in the image below):

![image](https://github.com/opportunity-hack/evs/assets/93843523/105b6cfe-58bf-4038-8a42-376de407e8c8)

I will check with Amy about whether or not this is sufficient in our upcoming meeting.

**Comment by benhsm** [comment]
I demoed this feature for Amy, and she indicated that the way it works now would be sufficient to fulfill this need, but I'm going to leave this issue open for now because this can probably be improved significantly.
