### ISSUE TITLE
Horse Assignments [Needs more details from Amy]

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/evs#16]
As it stands today, we need to understand what an instructor would want to see here - volunteers don't see horse assignments.

6. Horse assignments on this is an amazing feature! I really think it will help everything run much more smoothly. Is there a way to make 2 separate views for this? One for instructors and one for volunteers? Some of our instructors don't need volunteer help but this information known earlier than when they show up to teach would be amazing.
- It is definitely possible to make separate views for this. Right now the assignments view is only visible to administrators. I just need to know who should be able to see what, and then it should be relatively easy to make separate views.

**Comment by benhsm** [comment]
Issue #12 is a description of a feature aimed at addressing this

**Comment by gregv** [comment]
Adding this to #12
