### ISSUE TITLE
Event Creation Missing Horse Error

### ISSUE THREAD

**Issue by parkerdavis1** [opportunity-hack/evs#19]
When creating an event without assigning the 'Horses' field, a generic Error creating event message is thrown but there is no indication that the Horses field is required. A more helpful error message is needed.

**Comment by benhsm** [comment]
Based on recent requirements conversations, the plan now is to make 'Horses' a non-required field - there are event types which will have no associated horses.

**Comment by parkerdavis1** [comment]
In that case, the app should be able to create an event without a horse and not throw an "Error creating event" message 👍

**Comment by benhsm** [comment]
Should be addressed by 7cbf31cea1edf77e8ff199f628107fc71a632c71
