### ISSUE TITLE
Email and Username case constraints

### ISSUE THREAD

**Issue by parkerdavis1** [opportunity-hack/evs#20]
The database accepts the same email and username multiple times with different casing. 

test@test.com vs Test@test.com are treated as different emails with different accounts.
ExampleUserName vs exampleusername are treated as different usernames.

**Comment by benhsm** [comment]
In the case of usernames, this behavior is as expected and desired. Things seem a little murkier for email addresses.

From what I can see from the RFCs, the local part of an email is case sensitive, so test@test.com and Test@test.com are technically different addresses; however, the domain part is case insensitive, so test@test.com and test@Test.com are technically the same. 

Of course, most providers seem treat emails as simply case insensitive, so it may sense for us to follow suit and treat emails address strings with different case as the same address in every case.

**Comment by parkerdavis1** [comment]
I agree.

Are the usernames being used for anything other than logging in? Simplifying by dropping the username altogether and using email and password to log in would make the most sense to me. Easier to remember, no username conflicts to deal with. As far as I can tell, the ‘Name’ is the only data being displayed anywhere. 

Obviously low priority for MVP, but putting it out there nonetheless.

**Comment by benhsm** [comment]
Yeah, it's questionable whether usernames are even necessary to track for our purposes. They are useful in the current setup right now for having legible profile routes - `https://<sitename>/users/<username>`, but it's unclear whether that functionality itself is necessary.

Definitely something that could warrant further consideration, but yeah not going to make the difference between minimum-viable and not. On the other hand, it's not something we're going to be able to change easily once the system is actually in use.

**Comment by benhsm** [comment]
I think it's arguable that it's useful to be able to disambiguate users with the same names using a human manageable string that is guaranteed unique but not a machine generated string, even for ad hoc admin purposes, so I'm going to err towards keeping the username field.

**Comment by gregv** [comment]
Closing this with the most recent PR
