### ISSUE TITLE
Edit User Form (Birthday, Is an instructor checkbox)

### ISSUE THREAD

**Issue by parkerdavis1** [opportunity-hack/evs#22]
The **Edit User** form is not loading the user's birthday if it exists and is requiring inputting a birthday before changes can be saved. I spent some time looking into this but have not cracked why this is happening...

Also, the 'Is an instructor' checkbox is returning a string not boolean when checked, causing an error. 

Ben mentioned these bugs in the slack yesterday.

**Comment by benhsm** [comment]
This is an issue with the zod schema being used for validation. I'll get to this shortly.

**Comment by benhsm** [comment]
These problems should be fixed by fe0f72a9ed1567da640cb9962332b900dd3319e7
