### ISSUE TITLE
Bug: Registration emails display times in UTC

### ISSUE THREAD

**Issue by benhsm** [opportunity-hack/evs#41]
The datetimes displayed in the browser know the user's timezone and display properly in that timezone, but the times used in the post-registration emails are formatted and rendered on the server and use the server's configured timezone, which is UTC by default for our fly instances. The times in the ics attachments are displayed correctly by email clients. 

We should decide how to handle this. We can configure our docker images to have a particular timezone corresponding with the one we expect users of the site to be in. We could drop the formatted times from the formatted dates and times from the emails all together. That would be simpler, but my worry in that case would be users with email clients that don't support integrations with icalendar attachments.

**Comment by AceGabrielFigueroa** [comment]
Is the website planned to be used at one or more locations? Having configurable setup file might be worth looking into in the long run.

**Comment by benhsm** [comment]
We would probably configure this timezone as an environment variable on the docker image

**Comment by benhsm** [comment]
There are changes in the upstream starter project we should pull to address this: https://github.com/epicweb-dev/epic-stack/blob/839a39dc119984d34715886923b612edfd07617a/docs/timezone.md?plain=1#L20

**Comment by parkerdavis1** [comment]
Yeah, I was looking at those client hints the other day. That is theoretically more flexible but realistically for this particular application I can't imagine a scenario when Arizona time would not be what is wanted. This makes me think there is less room for error with selectively hard coding the timezone offset in a docker environment variable and indicating Arizona time/Mountain Time in the UI. We don't do daylight savings in AZ so no problem. But yeah, probably worth discussing more in-depth sometime.

**Comment by parkerdavis1** [comment]
Has this been resolved? It seems to work fine on the staging site.

**Comment by benhsm** [comment]
Yeah, the correct time should be displayed for our users with the recent configuration changes, but I'd like to add some timezone info to the UI + confirm some things about how things work in certain cases before closing this

**Comment by gregv** [comment]
So far we only deploy this in locations where users are on the same TZ, so closing this for now
