### ISSUE TITLE
Reword 2nd checkbox in the onboarding process

### ISSUE THREAD

**Issue by AceGabrielFigueroa** [opportunity-hack/evs#45]
Currently it says 
`Would you like to receive special discounts and offers?`

![aeighe](https://github.com/opportunity-hack/evs/assets/6834125/896a9c7f-1c9d-4da4-aa32-53f545d9c806)

I assume this would be used to email the user on upcoming big events, and or changes rather than "discounts/offers",
so something like 
`Would you like to subscribe to our newsletter?` or `Would you like to receive emails on big events/changes?`

**Comment by benhsm** [comment]
Right, this is a good thing to keep track of. It's also worth noting here that we aren't actually keeping track of subscription status at all, and this is something that needs to be implemented

**Comment by AceGabrielFigueroa** [comment]
would this be a bool in the db under user table? and would there be more user preferences added later?

**Comment by benhsm** [comment]
Yes, for now it would probably just be a binary flag indicating that user either gets emails or doesn't. Conceivably, a user might want more finer grained control, e.g. to hear emails about one volunteer role type and not others, but that's not necessary right now.

The challenge that's lurking here is the functionality for letting the admins send arbitrary emails to volunteers. E.g., every now and then, on an ad hoc basis, emails might go out saying "hey, we need some extra volunteers on Tuesday and Thursday this week"

**Comment by gregv** [comment]
Closing as fixed
![image](https://github.com/opportunity-hack/evs/assets/6913307/1f0479bd-3cee-48d5-89a5-113ba56576b9)
