### ISSUE TITLE
Feature: Send out event (ics) reminders to people who volunteer for events

### ISSUE THREAD

**Issue by benhsm** [opportunity-hack/evs#5]
Resend Doc: https://resend.com/docs/api-reference/emails/send-email
<img width="573" alt="image" src="https://github.com/opportunity-hack/evs/assets/6913307/e6f87893-071c-42cc-b396-fd6a39eea739">

# Example Code (from ChatGPT-4)
```
const nodemailer = require('nodemailer');
const sgTransport = require('nodemailer-sendgrid-transport');
const ics = require('ics');
const fs = require('fs');

// Event definition
let event = {
  start: [2023, 7, 30, 10, 0],  // Start time, formatted as: [YEAR, MONTH, DAY, HOUR, MINUTE]
  duration: { hours: 2 },  // Duration: 2 hours
  title: 'Meeting with Bob',  // Event title
  description: 'Discuss about the upcoming project',  // Event description
  location: 'Office',  // Event location
  organizer: { name: 'Alice', email: 'alice@example.com' },  // Event organizer
  attendees: [  // Attendees of the event
    { name: 'Bob', email: 'bob@example.com' }
  ]
};

ics.createEvent(event, (error, value) => {
  if (error) {
    console.log(error);
    return;
  }

  fs.writeFileSync('event.ics', value);
  
  // Your SendGrid API Key
  const options = {
    auth: {
      api_key: 'Your_SendGrid_API_Key'
    }
  };

  const mailer = nodemailer.createTransport(sgTransport(options));
  
  const email = {
    to: ['bob@example.com'],
    from: 'alice@example.com',
    subject: 'Meeting Invitation',
    text: 'Please find attached the invitation to the meeting.',
    attachments: [
      {
        filename: 'event.ics',
        path: './event.ics',
        contentType: 'text/calendar'
      }
    ]
  };
  
  mailer.sendMail(email, function(err, res) {
    if (err) { 
      console.log(err) 
    }
    console.log(res);
  });
});
```

# Overview
From [this Slack post](https://opportunity-hack.slack.com/archives/C01CMCF4BUN/p1688697090652109?thread_ts=1688675690.117329&cid=C01CMCF4BUN)
4. Will there be reminders sent out of times that volunteers have signed up for (manual or automatically)?
- The way I would try to do this is by sending out calendar event emails to volunteers automatically whenever they sign up for an event. This could integrate with their email application (Gmail, Outlook, etc) to give them reminders. Other solutions, like sending an email to volunteers a certain amount of time before an event happens, are somewhat harder to do.

Probably to be implemented using icalendar attachments. Going to try to avoid using background jobs for this at this point.

**Comment by benhsm** [comment]
Done as of 7e47385448843fea22b3fc99405b64bf82cba08a

**Comment by gregv** [comment]
I think we still need to add a calendar link for iCal or GCal so that people can be reminded of their session

**Comment by benhsm** [comment]
I spent some time trying to attach ICS files to outgoing emails, but I wasn't able to figure out how to do this through the resend API. What I'm thinking now is that we can generate files for each user's schedule of registered events, serve them off a resource route, and link to them from the emails. Not sure what this will take or if there are better ways to do this.

**Comment by benhsm** [comment]
Marking this as P0 because this is needed to have feature parity with the old solution currently in use

**Comment by gregv** [comment]
This is fixed
![image](https://github.com/opportunity-hack/evs/assets/6913307/5668bacb-14bb-4020-937d-d342cb2bd426)
