### ISSUE TITLE
Unregistering for an event doesn't send an email

### ISSUE THREAD

**Issue by jotpowers** [opportunity-hack/evs#67]
If I register for an event I get an "Event Registration Notification" with the corresponding calendar invite.  But unregistering doesn't send an email to notify that I'm no longer registered, so could lead to calendar confusion for the volunteer as well as just being inconsistent (I'd expect both actions to send email or neither, but not a hybrid)

**Comment by gregv** [comment]
![image](https://github.com/opportunity-hack/evs/assets/6913307/d660610c-7151-4d27-b359-f2310fb6ede1)
Fixed!
