### ISSUE TITLE
Registration:  Not obvious that username can't be email 

### ISSUE THREAD

**Issue by jotpowers** [opportunity-hack/evs#68]
Tried to use my email address for the registration and it appropriately errored and said I couldn't use special characters.   

Not to solution, but... However, maybe it would be better to have some description for that box that says something like "This will be your display name" (which honestly, I think is horrible text) or just a description of what characters are allowed so that people don't try to use their email addresses.  Or allow email addresses?

**Comment by gregv** [comment]
Here's what we have today
![image](https://github.com/opportunity-hack/evs/assets/6913307/95d57dca-3303-4c53-87ba-7010e9580211)
![image](https://github.com/opportunity-hack/evs/assets/6913307/451cdd0b-068b-421e-9347-ad30e9dd2933)

**Comment by gregv** [comment]
Making this change to be more specific
![image](https://github.com/opportunity-hack/evs/assets/6913307/ce58897e-8a1a-4ce8-93fe-5b1dca42aee7)

**Comment by gregv** [comment]
Fixed in prod - closing
![image](https://github.com/opportunity-hack/evs/assets/6913307/aa637766-efdb-4791-a764-4d215665a258)
