### ISSUE TITLE
Dark mode user profile UI enhancements

### ISSUE THREAD

**Issue by komal-saini** [opportunity-hack/evs#69]
**Overview**
The current dark mode implementation on the profile page can be improved to increase readability. 

**Suggestions**
- The user icon silhouette is hard to see in dark mode against the dark background - changing the contrast or colour can make this more visible 
- The button in the top-right corner where the user's name is for navigation purposes can be made to stand out more by changing the colour of the button

<img width="1492" alt="Screenshot 2023-12-25 at 9 04 24 PM" src="https://github.com/opportunity-hack/evs/assets/52506101/a736d6ac-7655-46ca-9272-1d385b2ddd4c">

**Comment by gregv** [comment]
Made this more obvious with a different default user image
![image](https://github.com/opportunity-hack/evs/assets/6913307/6bc2477f-d855-482d-94be-3ac46a8a39d8)
![image](https://github.com/opportunity-hack/evs/assets/6913307/25f0b4b8-b4b2-4ccb-a77a-5a065acb1867)

Also update horse icon while I was at it
![image](https://github.com/opportunity-hack/evs/assets/6913307/87acc46a-3816-4ffd-9fd5-6fec8389c8ed)

**Comment by parkerdavis1** [comment]
I was just doing the same(ish) thing 😂
![Screenshot 2023-12-29 at 12 35 48 PM](https://github.com/opportunity-hack/evs/assets/92223355/090fb993-0c03-4838-873f-47572bc4cfe3)

**Comment by gregv** [comment]
lol!
Fixed in prod
![image](https://github.com/opportunity-hack/evs/assets/6913307/ba4e3b67-baaa-4117-8a01-45a6a3224f03)
