### ISSUE TITLE
Past events persist when filtering to show only events that need volunteers 

### ISSUE THREAD

**Issue by komal-saini** [opportunity-hack/evs#70]
**Overview**
The calendar feature includes a toggle to 'Show only events that need more volunteers.' However, when this filter is activated, it does not hide past events as expected. This issue leads to a cluttered view and confusion for users trying to find events to volunteer for.

**Suggestion**
Implement a check within the filter function to ensure that only future events are displayed when the toggle is activated.

<img width="2529" alt="Screenshot 2023-12-25 at 9 12 59 PM" src="https://github.com/opportunity-hack/evs/assets/52506101/b6e4e83a-2855-41d6-83e7-20cd7354c89d">

**Comment by parkerdavis1** [comment]
Good call! Modified eventsThatNeedHelp filter to exclude past events: https://github.com/opportunity-hack/evs/commit/347faad84c162b5beafc4a7bb143bf8ccc512de3

**Comment by gregv** [comment]
Validated in prod - ty @parkerdavis1 and @komal-saini !! 🎉🎉🎉🎉🎉

# Before
![image](https://github.com/opportunity-hack/evs/assets/6913307/4ae38ffa-e814-46e5-8517-59ebd8b4344c)

# After
![image](https://github.com/opportunity-hack/evs/assets/6913307/807370fe-189f-43a9-a28a-452810f08b02)

# Created event that occurs in 1 hour and tested to ensure this works for same-day
![image](https://github.com/opportunity-hack/evs/assets/6913307/e8e7b3f2-113b-4cd2-a4c8-d2d74f61ddeb)
