### ISSUE TITLE
Bug: Email verification Link Doesn't work

### ISSUE THREAD

**Issue by leonkoech** [opportunity-hack/evs#71]
### Please note
- copy-pasting the link into the login link works
- Was tested on Chrome, Windows 11

After signing up for an account and receiving the email with the verification code, the link doesn't work. It returns an application error.

## Steps to recreate 
1. Sign up for an account with the signup secret
2. After receiving the email, click on the link on the email

## Expected behavior
When a user clicks the link the page should load and verify the user

## Browser and Device Information:
Browser: Chrome
Operating System: Windows
Device: Laptop

## See attached screenshots
![Screenshot 2023-12-27 091428](https://github.com/opportunity-hack/evs/assets/39020723/3d670727-319a-40a3-aa5f-7f8862a7d898)
![Screenshot 2023-12-27 091409](https://github.com/opportunity-hack/evs/assets/39020723/d8855397-3ec1-46e2-bf9c-52b5b8342bb1)

**Comment by leonkoech** [comment]
## Follow-up
After testing with another account, the link seems to be working 😵‍💫

Let me know if I should close it

**Comment by benhsm** [comment]
Thank you for testing this! It would certainly be problem if failure to verify via link is happening in some cases and not others (and I think this isn't the first time we've seen this in an end to end test) - so let's keep this open for now. If you could figure out anything about what differentiates those cases, that would be immensely helpful. In any case, I will try to reproduce this myself and investigate later on.

**Comment by gregv** [comment]
We spoke about this in Friday standup, could be related to #65

Current workaround is to only have a single DB running to avoid load balancing to the read-only replica and thus not allowing the write to save

**Comment by gregv** [comment]
Fix for this is #83 - closing
