### ISSUE TITLE
Bug: Character Limit For Phone number Length

### ISSUE THREAD

**Issue by leonkoech** [opportunity-hack/evs#73]
## Description

**Please Note**
This bug is more of a request, tried adding an impact section below.

In the onboarding section for entering my profile's phone number, I added 17 characters to my phone number field. This exceeded the typical format for a phone number (around 10-12 digits). The system accepted the invalid entry and allowed me to continue the onboarding process without any error message or warning about the incorrect format.
I also tried this on the Edit profile page as shown in the screenshots at the bottom. However, this time I added 4 to the previous 17.

## Steps to reproduce 

1. During onboarding, exceed the total character count for phone numbers 
2. Navigate to profile > Edit Profile > Edit the phone number

## Expected Behavior

The phone number field should validate the input and prevent users from entering more than the allowed number of characters.
If the entered number exceeds the limit, an error message should appear informing the user about the incorrect format and requiring them to enter a valid phone number.

## Impact

1. Inaccurate Data
3. Data inconsistency

## Screenshots
![Screenshot 2023-12-27 094020](https://github.com/opportunity-hack/evs/assets/39020723/368c7da3-df16-474a-a7fd-db4178c8dec0)

![Screenshot 2023-12-27 094041](https://github.com/opportunity-hack/evs/assets/39020723/c0ee71e1-afe0-4083-8ef5-daf3e6b4fab3)
![Screenshot 2023-12-27 094957](https://github.com/opportunity-hack/evs/assets/39020723/ee7fe5fc-cfaa-4d5b-ad3c-880cb7c1cdd7)

**Comment by parkerdavis1** [comment]
Good catch and a simple fix. Should be fixed with https://github.com/opportunity-hack/evs/commit/1900d805bf3a2d2342773853457e2a2378ee18aa

**Comment by gregv** [comment]
Tested on Prod - looks good! ty @parkerdavis1  and @leonkoech !
![image](https://github.com/opportunity-hack/evs/assets/6913307/75c85221-c935-48b4-8064-e4121c148502)
![image](https://github.com/opportunity-hack/evs/assets/6913307/7b484ac6-1e72-4e79-ad83-f3868704373d)
![image](https://github.com/opportunity-hack/evs/assets/6913307/e0ec3935-0db3-4ebc-902d-2488819326f1)
![image](https://github.com/opportunity-hack/evs/assets/6913307/71237dd4-3e67-4bda-b28c-da0bc25005de)
