### ISSUE TITLE
Unclear that I've already registered when clicking verification link

### ISSUE THREAD

**Issue by victorialo** [opportunity-hack/evs#77]
I already manually registered and verified using the code. I decided to go back and reclick the link and got this message:
![IMG_9249](https://github.com/opportunity-hack/evs/assets/4009775/7487ac9a-1ac3-49d1-b180-1da552aa143b)
I think the message saying it's an invalid code is not accurate - it's that I already have an account and/or that the code has been used. 
Best case is to tell me I already have an active account.

**Comment by gregv** [comment]
Good one!!

**Comment by gregv** [comment]
Fix for this is #83 - closing this
