### ISSUE TITLE
Autofill 1 for phone number 

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/evs#78]
> It autofilled a 1 (US country code) for me - it's probably better to make it clear in the original input that you only want 10 digits!

https://opportunity-hack.slack.com/archives/C1Q6YHXQU/p1704010590395969?thread_ts=1703282192.049909&cid=C1Q6YHXQU

**Comment by gregv** [comment]
Sent in slack by @victorialo

**Comment by parkerdavis1** [comment]
Addressed this issue with d2ed1ec0b9f59306c1ade7b09e6e236ef218fd59
<img width="1542" alt="Screenshot 2024-01-08 at 12 59 00 PM" src="https://github.com/opportunity-hack/evs/assets/92223355/be655e17-10cd-4089-874e-415f78f29971">

**Comment by gregv** [comment]
LGTM!
