### ISSUE TITLE
Username already exists error

### ISSUE THREAD

**Issue by parkerdavis1** [opportunity-hack/evs#8]
When onboarding, if you choose a username that already exists in the database and you submit the form, instead of a validation error being shown on the form, a prisma error is thrown on the page. 

![image](https://github.com/opportunity-hack/evs/assets/92223355/0f04f540-0401-4d05-9d05-f9379ffac09d)

**Comment by benhsm** [comment]
Good catch! This should be fixed by 14e26a3a14af72b63bdd9b3f320817597a686af3
