### ISSUE TITLE
403 Error when Horse Leader Registers for Event

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/evs#81]
Found a bug: getting a 403 when I try to register for a slot as a horse leader (when the user is a horse leader)

[Slack Message](https://opportunity-hack.slack.com/archives/C01CMCF4BUN/p1712432042255159)

**Comment by parkerdavis1** [comment]
I'll take a look later next week 👍

**Comment by parkerdavis1** [comment]
Just kidding, easy fix 3668aeee100e3319e2bdbf156711ec456010f6bf

**Comment by gregv** [comment]
Works like a charm!
![image](https://github.com/opportunity-hack/evs/assets/6913307/a17f843b-fcca-40f1-aad2-0a8fd9c03bc4)
